# Generated by Django 5.1.2 on 2024-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAmbientalPersona',
            fields=[
                ('id_actividadambiental', models.AutoField(primary_key=True, serialize=False)),
                ('desarrolla_aambiental', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dasarrolla actividad ambiental',
                'db_table': 'eco_gsc_aambiental',
            },
        ),
        migrations.CreateModel(
            name='ActividadesColectivo',
            fields=[
                ('id_acolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_actividad', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'actividadeds del colectivo',
                'db_table': 'eco_gsc_acolectivo',
            },
        ),
        migrations.CreateModel(
            name='ActividadPersonaColectivo',
            fields=[
                ('id_apcolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_actividad', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades de las personas dentro del colectivo',
                'db_table': 'eco_gsc_apcolectivo',
            },
        ),
        migrations.CreateModel(
            name='cantidadPersonasAfrocolombianos',
            fields=[
                ('id_cpafrocolombiano', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_pafrocolombiano', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas afrocolombianos del colectivo',
                'db_table': 'eco_gsc_cpafrocolombiano',
            },
        ),
        migrations.CreateModel(
            name='CantidadPersonasDiscapacidad',
            fields=[
                ('id_cpdiscapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_pdiscapacidad', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas con discapacidad del colectivo',
                'db_table': 'eco_gsc_cpdiscapacidad',
            },
        ),
        migrations.CreateModel(
            name='CantidadPersonasIndigena',
            fields=[
                ('id_cpindigena', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_pindigena', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas indígenas del colectivo',
                'db_table': 'eco_gsc_cpindigena',
            },
        ),
        migrations.CreateModel(
            name='cantidadPersonasNegro',
            fields=[
                ('id_cpnegro', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_pnegro', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas negras del colectivo',
                'db_table': 'eco_gsc_cpnegro',
            },
        ),
        migrations.CreateModel(
            name='cantidadPersonasPalenquero',
            fields=[
                ('id_cppalenquero', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ppalenquero', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas palenqueros del colectivo',
                'db_table': 'eco_gsc_cppalenquero',
            },
        ),
        migrations.CreateModel(
            name='cantidadPersonasRaizal',
            fields=[
                ('id_cpraizal', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_praizal', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas raizales del colectivo',
                'db_table': 'eco_gsc_cpraizal',
            },
        ),
        migrations.CreateModel(
            name='cantidadPersonasRomGitano',
            fields=[
                ('id_cpromgitano', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_promgitano', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cantidad de personas rom o gitanos del colectivo',
                'db_table': 'eco_gsc_cpromgitano',
            },
        ),
        migrations.CreateModel(
            name='CargoOrganizacion',
            fields=[
                ('id_corganizacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_corganizacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cargos de las organizaciones poblacion 2',
                'db_table': 'eco_gsc_corganizacion',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPnis',
            fields=[
                ('id_categoriapnis', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoriapnis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias para el pnis',
                'db_table': 'eco_bas_categoriapnis',
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id_consentimiento', models.AutoField(primary_key=True, serialize=False)),
                ('acepta_tdpersonales', models.BooleanField()),
                ('autoriza_pnacional', models.BooleanField()),
                ('autoriza_cmujeres', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Consentimiento de la persona',
                'db_table': 'eco_gsc_consentimiento',
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoColectivo',
            fields=[
                ('id_cocolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('acepta_tdpersonales', models.BooleanField()),
                ('autoriza_mpfpublica', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Consentimiento del colectivo',
                'db_table': 'eco_sis_consentimientoColectivo',
            },
        ),
        migrations.CreateModel(
            name='CorrespondenciaColectivo',
            fields=[
                ('id_ccolectivo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Dirección de correspondencia del colectivo',
                'db_table': 'eco_gsc_ccolectivo',
            },
        ),
        migrations.CreateModel(
            name='DatosPnis',
            fields=[
                ('id_pnis', models.AutoField(primary_key=True, serialize=False)),
                ('pertenece_pnis', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Datos del PNIS',
                'db_table': 'eco_gsc_datospnis',
            },
        ),
        migrations.CreateModel(
            name='DireccionNotificacionPersona',
            fields=[
                ('id_notificacion', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Datos de nacimiento de la persona',
                'db_table': 'eco_gsc_npersona',
            },
        ),
        migrations.CreateModel(
            name='DispacidadPersona',
            fields=[
                ('id_dpersona', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Discapacidad de la persona',
                'db_table': 'eco_sac_discapacidadpersona',
            },
        ),
        migrations.CreateModel(
            name='EntidadAcreditadora',
            fields=[
                ('id_eacreditadora', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Entidad acreditadora',
                'db_table': 'eco_gsc_eacreditadora',
            },
        ),
        migrations.CreateModel(
            name='EntidadSolicitanteColectivo',
            fields=[
                ('id_esolicitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_esolicitante', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entidad solicitante',
                'db_table': 'eco_gsc_esolicitante',
            },
        ),
        migrations.CreateModel(
            name='EtnicoConcejo',
            fields=[
                ('id_etnicoconcejo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Otro grupo étnico de la persona',
                'db_table': 'eco_gsc_etnicoconcejo',
            },
        ),
        migrations.CreateModel(
            name='EtnicoIndigena',
            fields=[
                ('id_etnicoindigena', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Grupo étnico indígena de la persona',
                'db_table': 'eco_gsc_etnicoindigena',
            },
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('id_evidencias', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_evidencias', models.FileField(upload_to='evidencias/')),
            ],
            options={
                'verbose_name_plural': 'tabla para mantener las evidencias cargadas por el usuario.',
                'db_table': 'eco_doc_evidenciasRiesgo',
            },
        ),
        migrations.CreateModel(
            name='FilePoblacion',
            fields=[
                ('id_fpoblacion', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_fpoblacion', models.FileField(upload_to='poblacion_objeto/')),
            ],
            options={
                'verbose_name_plural': 'Documento de acreditacion poblacional.',
                'db_table': 'eco_doc_filepoblacion',
            },
        ),
        migrations.CreateModel(
            name='funcionColectivo',
            fields=[
                ('id_fcolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('organizacion_stnivel', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_funcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Función del colectivo',
                'db_table': 'eco_gsc_fcolectivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoEtnicoPersona',
            fields=[
                ('id_getnico', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Grupo étnico de la persona',
                'db_table': 'eco_gsc_grupoetnico',
            },
        ),
        migrations.CreateModel(
            name='GrupoIndigena',
            fields=[
                ('id_gindigena', models.AutoField(primary_key=True, serialize=False)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('resguardo', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('parcialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad_sregistro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupo indígena de la persona',
                'db_table': 'eco_gsc_grupoindigena',
            },
        ),
        migrations.CreateModel(
            name='HechoVictimizanteColectivo',
            fields=[
                ('id_hvcolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_hvcolectivo', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hechos victimizantes del colectivo',
                'db_table': 'eco_sis_hvcolectivo',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionMedio',
            fields=[
                ('id_identificacionmedio', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Identificacion de los medios de la situación de riesgo',
                'db_table': 'eco_gsc_identificacionmedio',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionPoblacionObjeto',
            fields=[
                ('id_ipobjeto', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Poblaciones objeto identificadas por la persona',
                'db_table': 'eco_gsc_ipobjeto',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionSituacion',
            fields=[
                ('id_identificacionSituacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Identificación de las situaciones de riesgo',
                'db_table': 'eco_gsc_identificacionsituacion',
            },
        ),
        migrations.CreateModel(
            name='IdPoblacion',
            fields=[
                ('id_ipoblacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Identificación de la población objeto',
                'db_table': 'eco_gsc_idpoblacion',
            },
        ),
        migrations.CreateModel(
            name='IdPoblacionColectivo',
            fields=[
                ('id_ipcolectivo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Identificación de la población objeto para colectivo',
                'db_table': 'eco_gsc_idpcolectivo',
            },
        ),
        migrations.CreateModel(
            name='IdRiesgo',
            fields=[
                ('id_iriesgo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Identificación del Riesgo',
                'db_table': 'eco_gsc_identificacionriesgo',
            },
        ),
        migrations.CreateModel(
            name='mcComisionInternacional',
            fields=[
                ('id_mccomision', models.AutoField(primary_key=True, serialize=False)),
                ('numero_medida', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'número medida cautelar comisión interamericana de derechos humanos',
                'db_table': 'eco_gsc_mccomision',
            },
        ),
        migrations.CreateModel(
            name='mcCorteInternacional',
            fields=[
                ('id_mccorte', models.AutoField(primary_key=True, serialize=False)),
                ('numero_medida', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'número medida cautelar corte interamericana de derechos humanos',
                'db_table': 'eco_gsc_mccorte',
            },
        ),
        migrations.CreateModel(
            name='mcJuezRepublica',
            fields=[
                ('id_mcjrepublica', models.AutoField(primary_key=True, serialize=False)),
                ('numero_medida', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'número medida cautelar otorgado por un juez de la república',
                'db_table': 'eco_gsc_mcjrepublica',
            },
        ),
        migrations.CreateModel(
            name='MedidaCautelarColectivo',
            fields=[
                ('id_mccolectivo', models.AutoField(primary_key=True, serialize=False)),
                ('es_bmcocomisionidhumanos', models.BooleanField(blank=True, default=False, null=True)),
                ('es_bmcocorteidhumanos', models.BooleanField(blank=True, default=False, null=True)),
                ('es_bmcojrepublica', models.BooleanField(blank=True, default=False, null=True)),
                ('es_bmpsesp', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Beneficiario de alguna medida cautelar',
                'db_table': 'eco_gsc_bmccolectivo',
            },
        ),
        migrations.CreateModel(
            name='MedidaCuatelarPersona',
            fields=[
                ('id_mcautelar', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Medida cautelar de la persona',
                'db_table': 'eco_gsc_mcautelar',
            },
        ),
        migrations.CreateModel(
            name='NombreIdentitario',
            fields=[
                ('id_identitario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_identitario', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nombre identitario',
                'db_table': 'eco_gsc_nidentitario',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_organizacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_organizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_pjuridica', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'eco_gsc_organizacion',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionPersona',
            fields=[
                ('id_orgpersona', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Organización a la que pertenece la persona',
                'db_table': 'eco_gsc_organizacionpersona',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionPolitica',
            fields=[
                ('id_porganizacion', models.AutoField(primary_key=True, serialize=False)),
                ('pertene_poprganizacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Organizaciones Politicas poblacion 1',
                'db_table': 'eco_gsc_porganizacion',
            },
        ),
        migrations.CreateModel(
            name='OtraOrganizacion',
            fields=[
                ('id_oorganizacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_oorganizacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Otro tipo de organización',
                'db_table': 'eco_gsc_oorganizacion',
            },
        ),
        migrations.CreateModel(
            name='OtraSituacionRiesgo',
            fields=[
                ('id_osriesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_osituacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Otra situación de riesgo',
                'db_table': 'eco_gsc_osriesgo',
            },
        ),
        migrations.CreateModel(
            name='OtroGrupoPersona',
            fields=[
                ('id_ogetnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ccomunitario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Otro grupo de la persona',
                'db_table': 'eco_gsc_ogetnico',
            },
        ),
        migrations.CreateModel(
            name='PersonasCargo',
            fields=[
                ('id_pcargo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numero_pcargo', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Número de personas a cargo',
                'db_table': 'eco_gsc_personascargo',
            },
        ),
        migrations.CreateModel(
            name='PersoneriaJuridica',
            fields=[
                ('id_pjuridica', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numero_pjuridica', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personería jurídica de la organización',
                'db_table': 'eco_gsc_pjorganizacion',
            },
        ),
        migrations.CreateModel(
            name='PoblacionColectivo',
            fields=[
                ('id_pcoelctivo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Poblacion al que pertenece el colectivo',
                'db_table': 'eco_gsc_poblacioncolectivo',
            },
        ),
        migrations.CreateModel(
            name='PoblacionColectivoSesp',
            fields=[
                ('id_pcsesp', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Poblacion al que pertenece el colectivo si es de la sesp',
                'db_table': 'eco_gsc_psesp',
            },
        ),
        migrations.CreateModel(
            name='PoblacionGeneralColectivo',
            fields=[
                ('id_tpgcolectivo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tpgcolectivo', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de poblacion general colectivo',
                'db_table': 'eco_bas_tpgcolectivo',
            },
        ),
        migrations.CreateModel(
            name='PoblacionObjeto',
            fields=[
                ('id_poblacionobjeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pobjeto', models.CharField(blank=True, max_length=700, null=True)),
                ('identificador', models.CharField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Listado de las poblaciones objeto',
                'db_table': 'eco_bas_poblacionobjeto',
            },
        ),
        migrations.CreateModel(
            name='RelatosHechos',
            fields=[
                ('id_rhechos', models.AutoField(primary_key=True, serialize=False)),
                ('relato_hechos', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Relato de los hechos victimizantes',
                'db_table': 'eco_gsc_relatohechos',
            },
        ),
        migrations.CreateModel(
            name='TipoCategoriaOrganizacion',
            fields=[
                ('id_catorganizacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_catorganizacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de organizaciones',
                'db_table': 'eco_bas_catorganizacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id_tdiscapacidad', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tdiscapacidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipo de discapacidad',
                'db_table': 'eco_bas_tipodiscapacidad',
            },
        ),
        migrations.CreateModel(
            name='tipoEntidadAcreditadora',
            fields=[
                ('id_teacreditadora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_teacreditadora', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entidades acreditadoras del colectivo',
                'db_table': 'eco_bas_teacolectivo',
            },
        ),
        migrations.CreateModel(
            name='TipoGrupoEtnico',
            fields=[
                ('id_tetnico', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tetnico', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipo de grupo étnico',
                'db_table': 'eco_bas_tipoetnico',
            },
        ),
        migrations.CreateModel(
            name='TipoMedidaCautelar',
            fields=[
                ('id_tmcautelar', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tmcautelar', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Tipo de medida cautelar de la persona',
                'db_table': 'eco_bas_tipomcautelar',
            },
        ),
        migrations.CreateModel(
            name='TipoMediosSituacion',
            fields=[
                ('id_msituacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_msituacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de medios por el que se presento la situación',
                'db_table': 'eco_bas_mediosituacion',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacionPersona',
            fields=[
                ('id_torganizacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_torganizacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipo de organizaciones',
                'db_table': 'eco_bas_tipoorganizacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPoblacion',
            fields=[
                ('id_tipopoblacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tpoblacion', models.CharField(blank=True, max_length=170, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de población objeto',
                'db_table': 'eco_bas_tipopoblacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPoblacionColectivo',
            fields=[
                ('id_tpcolectivo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tpcolectivo', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de poblacion colectivo',
                'db_table': 'eco_bas_tpoblacioncolectivo',
            },
        ),
        migrations.CreateModel(
            name='TipoPoblacionSesp',
            fields=[
                ('id_poblacionsesp', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_poblacionsesp', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de poblacion colectivo de la sesp',
                'db_table': 'eco_bas_tpcsesp',
            },
        ),
        migrations.CreateModel(
            name='TipoSituacionesRiesgo',
            fields=[
                ('id_tiporiesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sriesgo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de situaciones de riesgo',
                'db_table': 'eco_bas_tiporiesgo',
            },
        ),
    ]
