# Generated by Django 5.1.2 on 2024-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gsc', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadambientalpersona',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='actividadpersonacolectivo',
            name='persona_colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.personacolectivo'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasafrocolombianos',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasdiscapacidad',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasindigena',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasnegro',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonaspalenquero',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasraizal',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='cantidadpersonasromgitano',
            name='informacion_cfdiferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.informacióncolectivofactordiferencial'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='consentimientocolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='datospnis',
            name='categoria_pnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.categoriapnis'),
        ),
        migrations.AddField(
            model_name='direccionnotificacionpersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicospersona'),
        ),
        migrations.AddField(
            model_name='dispacidadpersona',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='entidadacreditadora',
            name='colectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='entidadsolicitantecolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='funcioncolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='grupoetnicopersona',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='etnicoindigena',
            name='grupo_etnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.grupoetnicopersona'),
        ),
        migrations.AddField(
            model_name='etnicoconcejo',
            name='grupo_etnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.grupoetnicopersona'),
        ),
        migrations.AddField(
            model_name='etnicoindigena',
            name='grupo_indigena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.grupoindigena'),
        ),
        migrations.AddField(
            model_name='hechovictimizantecolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='idpoblacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicospersona'),
        ),
        migrations.AddField(
            model_name='identificacionpoblacionobjeto',
            name='identificacion_poblacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacion'),
        ),
        migrations.AddField(
            model_name='filepoblacion',
            name='id_ipoblacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacion'),
        ),
        migrations.AddField(
            model_name='datospnis',
            name='poblacion_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacion'),
        ),
        migrations.AddField(
            model_name='cargoorganizacion',
            name='Poblacion_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacion'),
        ),
        migrations.AddField(
            model_name='idpoblacioncolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='actividadescolectivo',
            name='poblacion_colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacioncolectivo'),
        ),
        migrations.AddField(
            model_name='idriesgo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicospersona'),
        ),
        migrations.AddField(
            model_name='identificacionsituacion',
            name='identificacion_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idriesgo'),
        ),
        migrations.AddField(
            model_name='identificacionmedio',
            name='identificacion_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idriesgo'),
        ),
        migrations.AddField(
            model_name='evidencias',
            name='id_iriesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idriesgo'),
        ),
        migrations.AddField(
            model_name='medidacautelarcolectivo',
            name='colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datosbasicoscolectivos'),
        ),
        migrations.AddField(
            model_name='mcjuezrepublica',
            name='id_mccolectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.medidacautelarcolectivo'),
        ),
        migrations.AddField(
            model_name='mccorteinternacional',
            name='id_mccolectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.medidacautelarcolectivo'),
        ),
        migrations.AddField(
            model_name='mccomisioninternacional',
            name='id_mccolectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.medidacautelarcolectivo'),
        ),
        migrations.AddField(
            model_name='medidacuatelarpersona',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='nombreidentitario',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='organizacionpersona',
            name='cpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='organizacionpersona',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.organizacion'),
        ),
        migrations.AddField(
            model_name='organizacionpolitica',
            name='poblacion_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacion'),
        ),
        migrations.AddField(
            model_name='otraorganizacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.organizacion'),
        ),
        migrations.AddField(
            model_name='otrasituacionriesgo',
            name='identificacion_situacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idriesgo'),
        ),
        migrations.AddField(
            model_name='etnicoconcejo',
            name='otro_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.otrogrupopersona'),
        ),
        migrations.AddField(
            model_name='personascargo',
            name='factor_diferencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.datoscomplemetariospersona'),
        ),
        migrations.AddField(
            model_name='personeriajuridica',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.organizacion'),
        ),
        migrations.AddField(
            model_name='poblacioncolectivo',
            name='poblacion_colectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacioncolectivo'),
        ),
        migrations.AddField(
            model_name='poblacioncolectivosesp',
            name='poblacion_colectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsc.idpoblacioncolectivo'),
        ),
        migrations.AddField(
            model_name='identificacionpoblacionobjeto',
            name='poblacion_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.poblacionobjeto'),
        ),
        migrations.AddField(
            model_name='relatoshechos',
            name='identificacion_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.idriesgo'),
        ),
        migrations.AddField(
            model_name='organizacionpolitica',
            name='tipo_catorganizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipocategoriaorganizacion'),
        ),
        migrations.AddField(
            model_name='dispacidadpersona',
            name='tipo_discapacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipodiscapacidad'),
        ),
        migrations.AddField(
            model_name='entidadacreditadora',
            name='Tipo_eacreditadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsc.tipoentidadacreditadora'),
        ),
        migrations.AddField(
            model_name='grupoetnicopersona',
            name='tipo_getnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipogrupoetnico'),
        ),
        migrations.AddField(
            model_name='medidacuatelarpersona',
            name='tipo_mcautelar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipomedidacautelar'),
        ),
        migrations.AddField(
            model_name='identificacionmedio',
            name='medio_situacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipomediossituacion'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipoorganizacionpersona'),
        ),
        migrations.AddField(
            model_name='poblacionobjeto',
            name='tipo_poblacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipopoblacion'),
        ),
        migrations.AddField(
            model_name='tipopoblacioncolectivo',
            name='poblacion_gcolectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsc.poblaciongeneralcolectivo'),
        ),
        migrations.AddField(
            model_name='poblacioncolectivo',
            name='tipo_pcolectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipopoblacioncolectivo'),
        ),
        migrations.AddField(
            model_name='tipopoblacionsesp',
            name='tipo_poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsc.tipopoblacioncolectivo'),
        ),
        migrations.AddField(
            model_name='poblacioncolectivosesp',
            name='poblacion_sesp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tipopoblacionsesp'),
        ),
        migrations.AddField(
            model_name='identificacionsituacion',
            name='tipo_sriesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsc.tiposituacionesriesgo'),
        ),
    ]
