# Generated by Django 5.1.2 on 2024-10-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromisoReunion',
            fields=[
                ('id_compromiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_compromiso', models.CharField(blank=True, max_length=500, null=True)),
                ('compromiso_cumplido', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Compromisos de la reunion',
                'db_table': 'eco_reu_rcompromisos',
            },
        ),
        migrations.CreateModel(
            name='FechaReunion',
            fields=[
                ('id_fechareunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reunion', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'fecha y hora  de la reunión',
                'db_table': 'eco_reu_horareunion',
            },
        ),
        migrations.CreateModel(
            name='LlaveAsistenteReunion',
            fields=[
                ('id_lareunion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'llave de asistentes de la reunion',
                'db_table': 'eco_reu_llareunion',
            },
        ),
        migrations.CreateModel(
            name='LlaveCompromisoReunion',
            fields=[
                ('id_lrcompromiso', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'llave de compromisos de la reunion',
                'db_table': 'eco_reu_lrcompromisos',
            },
        ),
        migrations.CreateModel(
            name='LlaveConclusionReunion',
            fields=[
                ('id_tcreunion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'llave de conclusiones del los temas de la reunion',
                'db_table': 'eco_reu_llcreunion',
            },
        ),
        migrations.CreateModel(
            name='LlaveDesarrolloReunion',
            fields=[
                ('id_tdreunion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'llave de desarrollo del los temas de la reunion',
                'db_table': 'eco_reu_lldreunion',
            },
        ),
        migrations.CreateModel(
            name='LlaveResponsableReunion',
            fields=[
                ('id_lrreunion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'llave de responsables de la reunion',
                'db_table': 'eco_reu_llrreunion',
            },
        ),
        migrations.CreateModel(
            name='LugarReunion',
            fields=[
                ('id_lugarreunion', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'lugar de la UNP',
                'db_table': 'eco_reu_lugarreunion',
            },
        ),
        migrations.CreateModel(
            name='SedeUnp',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sedes de la UNP',
                'db_table': 'eco_bas_sede',
            },
        ),
        migrations.CreateModel(
            name='TemaReunion',
            fields=[
                ('id_temareunion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_temareunion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tema principal de la reunión',
                'db_table': 'eco_reu_temareunion',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoCompromiso',
            fields=[
                ('id_tecompromiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecompromiso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo de estados de los compromisos de la reunión',
                'db_table': 'eco_bas_tecompromiso',
            },
        ),
        migrations.CreateModel(
            name='EstadoCompromiso',
            fields=[
                ('id_estadocompromiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_compromiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.compromisoreunion')),
            ],
            options={
                'verbose_name_plural': 'Estado de los compromisos de la reunión',
                'db_table': 'eco_reu_estadocompromiso',
            },
        ),
        migrations.CreateModel(
            name='FechaCompromiso',
            fields=[
                ('id_fechacompromiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_iniciocompromiso', models.DateField(blank=True, null=True)),
                ('fecha_fincompromiso', models.DateField(blank=True, null=True)),
                ('id_compromiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.compromisoreunion')),
            ],
            options={
                'verbose_name_plural': 'fecha de los compromisos de la reunión',
                'db_table': 'eco_reu_fechacompromiso',
            },
        ),
        migrations.CreateModel(
            name='AsistenteReunion',
            fields=[
                ('id_areunion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llave_areunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llaveasistentereunion')),
            ],
            options={
                'verbose_name_plural': 'Asistentes a las reunion',
                'db_table': 'eco_reu_asistentereunion',
            },
        ),
        migrations.AddField(
            model_name='compromisoreunion',
            name='llave_compromiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llavecompromisoreunion'),
        ),
        migrations.CreateModel(
            name='ConclusionReunion',
            fields=[
                ('id_creunion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_conclucion', models.CharField(blank=True, max_length=200, null=True)),
                ('llave_creunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llaveconclusionreunion')),
            ],
            options={
                'verbose_name_plural': 'conclusiones del los temas de la reunion',
                'db_table': 'eco_reu_conclusionreunion',
            },
        ),
        migrations.CreateModel(
            name='DesarrolloReunion',
            fields=[
                ('id_dreunion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tema', models.CharField(blank=True, max_length=200, null=True)),
                ('llave_dreunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llavedesarrolloreunion')),
            ],
            options={
                'verbose_name_plural': 'desarrollo del los temas de la reunion',
                'db_table': 'eco_reu_desarrolloreunion',
            },
        ),
        migrations.CreateModel(
            name='RelatorReunion',
            fields=[
                ('id_relatorreunion', models.AutoField(primary_key=True, serialize=False)),
                ('llave_areunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llaveresponsablereunion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asistentes a las reunion',
                'db_table': 'eco_reu_relatorreunion',
            },
        ),
        migrations.CreateModel(
            name='ResponsableCompromiso',
            fields=[
                ('id_responsablecompromiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_compromiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.compromisoreunion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'responsable de los compromisos de la reunión',
                'db_table': 'eco_reu_responsablecompromiso',
            },
        ),
        migrations.CreateModel(
            name='ResponsableReunion',
            fields=[
                ('id_responsablereunion', models.AutoField(primary_key=True, serialize=False)),
                ('llave_areunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.llaveresponsablereunion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asistentes a las reunion',
                'db_table': 'eco_reu_responsablereunion',
            },
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.fechareunion')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.lugarreunion')),
            ],
            options={
                'verbose_name_plural': 'reuniones',
                'db_table': 'eco_reu_reunion',
            },
        ),
        migrations.AddField(
            model_name='llaveresponsablereunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.reuniones'),
        ),
        migrations.AddField(
            model_name='llavedesarrolloreunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.reuniones'),
        ),
        migrations.AddField(
            model_name='llaveconclusionreunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.reuniones'),
        ),
        migrations.AddField(
            model_name='llavecompromisoreunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.reuniones'),
        ),
        migrations.AddField(
            model_name='llaveasistentereunion',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.reuniones'),
        ),
    ]
