# Generated by Django 5.1.2 on 2024-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reuniones', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedeunp',
            name='Municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.municipio'),
        ),
        migrations.AddField(
            model_name='sedeunp',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.departamento'),
        ),
        migrations.AddField(
            model_name='lugarreunion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.sedeunp'),
        ),
        migrations.AddField(
            model_name='reuniones',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.temareunion'),
        ),
        migrations.AddField(
            model_name='estadocompromiso',
            name='estado_compromiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reuniones.tipoestadocompromiso'),
        ),
    ]
