# Generated by Django 5.1.2 on 2024-10-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sedeunp',
            old_name='Municipio',
            new_name='municipio',
        ),
    ]
