# Generated by Django 5.1.2 on 2024-10-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_dependencia_nombre_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='nombre_dependencia',
            field=models.CharField(max_length=70),
        ),
    ]
