# Generated by Django 5.1.2 on 2024-10-20 22:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsc', '0002_initial'),
        ('registro', '0003_rename_tiporura_tiporuta'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformaciónColectivoFactorDiferencial',
            new_name='ColectivoFDiferencial',
        ),
        migrations.RenameModel(
            old_name='DatosRepresentanteLegalMenor',
            new_name='DatosRepresentanteLegal',
        ),
        migrations.RenameModel(
            old_name='IdentificacionRepresentanteLegalMenor',
            new_name='IdentificacionRepresentante',
        ),
        migrations.RenameModel(
            old_name='NombreApellidoPersonaColectivo',
            new_name='NombrePersonaColectivo',
        ),
        migrations.RenameModel(
            old_name='direccionUrbana',
            new_name='UbicacionUrbana',
        ),
        migrations.CreateModel(
            name='GeoUrbana',
            fields=[
                ('id_geourbana', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.datosubicacion')),
            ],
            options={
                'verbose_name_plural': 'Geolocalización urbana',
                'db_table': 'eco_geo_urbana',
            },
        ),
    ]
