# Generated by Django 5.1.2 on 2024-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalSolicitud',
            fields=[
                ('id_csolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_csolicitud', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de medio o canal donde se realiza la solicitud',
                'db_table': 'eco_bas_canalsolicitud',
            },
        ),
        migrations.CreateModel(
            name='DiligenciaFormulario',
            fields=[
                ('id_dformulario', models.AutoField(primary_key=True, serialize=False)),
                ('primer_ndiligencia', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_ndiligencia', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_adiligencia', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_adiligencia', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto_tdiligencia', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_ediligencia', models.EmailField(blank=True, max_length=60, null=True)),
                ('entidad_solicitante', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos de quien diligencia el formulario',
                'db_table': 'eco_reg_dformulario',
            },
        ),
        migrations.CreateModel(
            name='EntidadrespondeLlamada',
            fields=[
                ('id_entidadresponde', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_entidadresponde', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_personaresponde', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos de la entidad que responde',
                'db_table': 'eco_reg_ellamada',
            },
        ),
        migrations.CreateModel(
            name='EstadoGeneral',
            fields=[
                ('id_egeneral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_egeneral', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados generales',
                'db_table': 'eco_bas_egeneral',
            },
        ),
        migrations.CreateModel(
            name='fechaDiligenciamientoFormulario',
            fields=[
                ('id_fdformulario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_dformulario', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'fecha de diligenciamiento del formualario',
                'db_table': 'eco_reg_fdiligenciamiento',
            },
        ),
        migrations.CreateModel(
            name='FechaHoraLlamada',
            fields=[
                ('id_fechahora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'fecha y hora de la llamada',
                'db_table': 'eco_reg_fhllamada',
            },
        ),
        migrations.CreateModel(
            name='FechaTerminos',
            fields=[
                ('id_fterminos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fecha terminos',
                'db_table': 'eco_reg_fterminos',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('diligencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.diligenciaformulario')),
                ('fecha_diligenciamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.fechadiligenciamientoformulario')),
            ],
            options={
                'verbose_name_plural': 'Datos del formulario',
                'db_table': 'eco_reg_formulario',
            },
        ),
        migrations.CreateModel(
            name='InformacionLlamada',
            fields=[
                ('id_infollamada', models.AutoField(primary_key=True, serialize=False)),
                ('numero_intentos', models.SmallIntegerField(blank=True, null=True)),
                ('observacion_llamada', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Información importante de la llamada',
                'db_table': 'eco_reg_infollamada',
            },
        ),
        migrations.CreateModel(
            name='lugarDiligenciamientoFormulario',
            fields=[
                ('id_ldiligenciamiento', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'lugar de diligenciamiento del formualario',
                'db_table': 'eco_reg_ldiligenciamiento',
            },
        ),
        migrations.CreateModel(
            name='MedioContactoLlamada',
            fields=[
                ('id_mcllamada', models.AutoField(primary_key=True, serialize=False)),
                ('celular_torigen', models.CharField(blank=True, max_length=12, null=True)),
                ('celular_tdestino', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'número de celular o teléfono donde se realiza la llamada y número de quién recibe',
                'db_table': 'eco_reg_mcllamada',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Registro',
                'db_table': 'eco_reg_registro',
            },
        ),
        migrations.CreateModel(
            name='RegistroLlamadas',
            fields=[
                ('id_rllamadas', models.AutoField(primary_key=True, serialize=False)),
                ('responde_solicitante', models.BooleanField(default=False)),
                ('responde_tercero', models.BooleanField(default=False)),
                ('responde_entidad', models.BooleanField(default=False)),
                ('tiene_dubicacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'regisros de llamadas',
                'db_table': 'eco_reg_rllamadas',
            },
        ),
        migrations.CreateModel(
            name='RespondeRuralLlamada',
            fields=[
                ('id_responderural', models.CharField(primary_key=True, serialize=False)),
                ('vereda', models.CharField(blank=True, max_length=30, null=True)),
                ('corregimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('centro_poblado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos de ubicación rural donde se encuentra el contactado',
                'db_table': 'eco_reg_urllamada',
            },
        ),
        migrations.CreateModel(
            name='RespondeUrbanaLlamada',
            fields=[
                ('id_respondeurbana', models.CharField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos de ubicación urbana donde se encuentra el contactado',
                'db_table': 'eco_reg_uullamada',
            },
        ),
        migrations.CreateModel(
            name='TerceroRespondeLlamada',
            fields=[
                ('id_terceroresponde', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_terceroresponde', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_respondetercero', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datos del tercero que responde',
                'db_table': 'eco_reg_tllamada',
            },
        ),
        migrations.CreateModel(
            name='TipoResultadoLlamada',
            fields=[
                ('id_trllamada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trllamada', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de resultados de la llamadas',
                'db_table': 'eco_bas_trllamadas',
            },
        ),
        migrations.CreateModel(
            name='TipoRura',
            fields=[
                ('id_truta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_truta', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de ruta',
                'db_table': 'eco_bas_ruta',
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id_traza', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'trazabilidad',
                'db_table': 'eco_reg_trazabilidad',
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadGeneral',
            fields=[
                ('id_trazabilidad', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'trazabilidad general',
                'db_table': 'eco_reg_tgeneral',
            },
        ),
        migrations.CreateModel(
            name='UbicacionrespondeLlamada',
            fields=[
                ('id_ubicacionresponde', models.AutoField(primary_key=True, serialize=False)),
                ('responde_urbana', models.BooleanField(default=False)),
                ('responde_rural', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Datos de ubicación donde se encuentra el contactado',
                'db_table': 'eco_reg_ullamada',
            },
        ),
        migrations.CreateModel(
            name='EstadoEspecifico',
            fields=[
                ('id_eespecifico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_eespecifico', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.estadogeneral')),
            ],
            options={
                'verbose_name_plural': 'Estados específicos',
                'db_table': 'eco_bas_especifico',
            },
        ),
        migrations.CreateModel(
            name='FormularioColectivo',
            fields=[
                ('formulario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registro.formulario')),
            ],
            options={
                'verbose_name_plural': 'Datos del formulario colectivo',
                'db_table': 'eco_gsc_formulariocolectivo',
            },
            bases=('registro.formulario',),
        ),
        migrations.CreateModel(
            name='FormularioIndividual',
            fields=[
                ('formulario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registro.formulario')),
            ],
            options={
                'verbose_name_plural': 'Datos del formulario individual',
                'db_table': 'eco_reg_formularioindividual',
            },
            bases=('registro.formulario',),
        ),
    ]
