# Generated by Django 5.1.2 on 2024-10-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoRura',
            new_name='TipoRuta',
        ),
    ]
